apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: gokit-gorillakit-enginesvc-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: gokit-gorillakit-enginesvc
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      minAllowed:
        cpu: 100m
        memory: 100Miå
      maxAllowed:
        cpu: 200m
        memory: 200Mi
      controlledResources: ["cpu", "memory"]