# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gokit-gorillakit-enginesvc
  namespace: enginesvc
  labels:
    app: gokit-gorillakit-enginesvc
spec:
  selector:
    matchLabels:
      app: gokit-gorillakit-enginesvc
  replicas: 2
  template:
    metadata:
      labels:
        app:  gokit-gorillakit-enginesvc
    spec:
      containers:
      - name:  gokit-gorillakit-enginesvc
        image:  isgogolgo13/gokit-gorillakit-enginesvc:master
        resources:
          requests:
            cpu: "250m"
            memory: "250Mi"
          limits:
            cpu: "1"
            memory: "2000Mi"
        ports:
        - containerPort: 8080
      restartPolicy: Always




